<?php


namespace Mcarral\Sifen\Entities\ElectronicDocumentEventSections;


/**
 * Class EventCompliance
 * @package Mcarral\Sifen\Entities\ElectronicDocumentEventSections
 * @property string Id
 * @property integer iTipConf
 * @property string dFecRecep
 */
class EventAccordance extends EventBase {

    protected $attributes = [
        'Id' => null, 'iTipConf' => null, 'dFecRecep' => null,
    ];

    protected $fillable = ['iTipConf', 'dFecRecep'];

    public function defaults()
    {
        parent::defaults(); // TODO: Change the autogenerated stub
        $this->iTipConf = 1;

        return $this;
    }

    public function schema()
    {
        return "";
    }

    public function sectionName()
    {
        return 'rGeVeConf';
    }

}