<?php


namespace Mcarral\Sifen\Entities\ElectronicDocumentEventSections;


/**
 * Class EventCompliance
 * @package Mcarral\Sifen\Entities\ElectronicDocumentEventSections
 * @property string Id
 * @property string mOtEve
 */
class EventDisagreement extends EventBase {

    protected $attributes = [
        'Id' => null, 'mOtEve' => null,
    ];

    protected $fillable = ['mOtEve'];

    public function defaults()
    {
        parent::defaults(); // TODO: Change the autogenerated stub
        $this->mOtEve = "No conforme con los datos emitidos";

        return $this;
    }

    public function schema()
    {
        return "";
    }

    public function sectionName()
    {
        return 'rGeVeDisconf';
    }

}