<?php

namespace Mcarral\Sifen\Entities\ElectronicDocumentEventSections;

/**
 * Class EventCanceled
 * @package Mcarral\Sifen\Entities\ElectronicDocumentSections
 * @property string Id
 * @property string mOtEve
 */
class EventCanceled extends EventBase {

    protected $attributes = ['Id' => null, 'mOtEve' => null];

    protected $fillable = ['mOtEve'];

    public function sectionName()
    {
        return 'rGeVeCan';
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            'mOtEve' => ['required', 'string', 'between:5,150'],
        ]); // TODO: Change the autogenerated stub
    }

    public function rulesAttributes()
    {
        return array_merge(parent::rulesAttributes(), [
            'mOtEve' => 'Motivo del Evento',
        ]); // TODO: Change the autogenerated stub
    }

    public function schema()
    {
        return 'RecEventoCanc';
    }
}