<?php

namespace Mcarral\Sifen\Entities\ElectronicDocumentEventSections;

/**
 * Class EventNomination
 * @property string Id
 * @property string mOtEve
 * @property int iNatRec
 * @property int iTiOpe
 * @property int cPaisRec
 * @property string dDesPaisRe
 * @property string dNomRec
 * @property integer iTiContRec
 * @property string dRucRec
 * @property int dDVRec
 * @property int iTipIDRec
 * @property string dDTipIDRec
 * @property string dNumIDRec
 * @property string dNomFanRec
 * @property string cDepRec
 * @property string dDesDepRec
 * @property string cDisRec
 * @property string dDesDisRec
 * @property string cCiuRec
 * @property string dDesCiuRec
 * @property string dCelRec
 * @property string dEmailRec
 * @property string dCodCliente
 */
class EventNomination extends EventBase
{

    protected $attributes = [
        'Id' => null, 'mOtEve' => null, 'iNatRec' => null, 'iTiOpe' => null,
        'cPaisRec' => null, 'dDesPaisRe' => null, "iTiContRec" => null,
        'dRucRec' => null, 'dDVRec' => null, 'iTipIDRec' => null, 'dDTipIDRec' => null,
        'dNumIDRec' => null, 'dNomRec' => null, 'dNomFanRec' => null, 'dDirRec' => null, 'dNumCasRec' => null,
        'dCodCliente' => null,
    ];

    protected $fillable = [
        'mOtEve', 'iNatRec', 'iTiOpe', 'cPaisRec', 'dDesPaisRe', 'iTiContRec', 'dRucRec', 'dDVRec',
        'iTipIDRec', 'dDTipIDRec', 'dNumIDRec', 'dNomRec', 'dNomFanRec', 'dDirRec', 'dNumCasRec', 'dCodCliente'
    ];

    public function sectionName()
    {
        return 'rGEveNom';
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            'mOtEve' => ['required', 'string', 'between:5,500'],
        ]); // TODO: Change the autogenerated stub
    }

    public function rulesAttributes()
    {
        return array_merge(parent::rulesAttributes(), [
            'mOtEve' => 'Motivo del Evento',
            'iNatRec' => 'Naturaleza del receptor',
            'iTiOpe' => 'Tipo de operación',
            'cPaisRec' => 'Código de país del receptor',
            'dDesPaisRe' => 'Descripción del país receptor',
            'dNomRec' => 'Nombre o razón social del receptor del DTE',
            'iTiContRec' => 'Tipo de contribuyente receptor',
            'dRucRec' => 'RUC del receptor',
            'dDVRec' => 'Dígito verificador del RUC del receptor',
            'iTipIDRec' => 'Tipo de documento de identidad del receptor',
        ]); // TODO: Change the autogenerated stub
    }

    public function schema()
    {
        return 'RecEventoNom';
    }

}
