<?php

namespace Mcarral\Sifen\Entities\ElectronicDocumentEventSections;

use Illuminate\Support\Arr;

class GroupTiEvt extends ElectronicDocumentSectionBase {

    protected $attributes = [
        'rGeVeCan' => null, 'rGeVeInu' => null, 'rGeVeNotRec' => null, 'rGeVeConf' => null, 'rGEveNom' => null,
        'rGeVeDisconf' => null, 'rGeVeDescon' => null,
    ];

    protected $fillable = ['rGeVeCan', 'rGeVeInu', 'rGeVeNotRec', 'rGeVeConf', 'rGEveNom', 'rGeVeDisconf', 'rGeVeDescon'];

    protected $classmap = [
        'rGeVeCan' => 'rEventCanceled', 'rGeVeInu' => 'rEventDisabled',
        'rGeVeNotRec' => 'rEventCompliance', 'rGeVeConf' => 'rEventAccordance',
        'rGEveNom' => 'rEventNomination',
        'rGeVeDisconf' => 'rEventDisagreement', 'rGeVeDescon' => 'rEventUnknown'
    ];

    /**
     * @return string
     */
    protected function currentEventSection()
    {
        foreach (EventRoot::$events as $type => $event) {
            if ($type !== $this->root()->ed()->event_type) continue;
            return $event[1];
        }

        return '';
    }

    public function toArray()
    {
        return Arr::only(parent::toArray(), $this->currentEventSection()); // TODO: Change the autogenerated stub
    }

}
