<?php

namespace Mcarral\Sifen\Entities\ElectronicDocumentSections;
use Illuminate\Support\Arr;

/**
 * Class CamNCDE
 * @property int iMotEmi
 * @property string dDesMotEmi
 * @package Mcarral\Sifen\Entities\ElectronicDocumentSections
 */
class CamNCDE extends ElectronicDocumentSectionBase {

    protected $attributes = ['iMotEmi' => null, 'dDesMotEmi' => null];

    static public $iMotEmiOptions = [
        1 => 'Anulación', 2 => 'Devolución', 3 => 'Descuento', 4 => 'Bonificación', 5 => 'Crédito incobrable',
        6 => 'Recupero de costo', 7 => 'Recupero de gasto', 8 => 'Ajuste de precio'
    ];

    public function defaults()
    {
        parent::defaults(); // TODO: Change the autogenerated stub
        $this->iMotEmi = 2;

        return $this;
    }

    public function getDDesMotEmiAttribute()
    {
        return (! is_null($this->iMotEmi)) ? Arr::get(static::$iMotEmiOptions, $this->iMotEmi, '') : null;
    }

}