<?php

namespace Mcarral\Sifen\Entities\ElectronicDocumentSections;

use Illuminate\Support\Arr;

/**
 * @property string dFeEmiDE
 * @property-read OpeCom gOpeCom
 * @property-read Emis gEmis
 * @property-read DatRec gDatRec
 * Class DatGralOpe
 * @package Mcarral\Sifen\Entities\ElectronicDocumentSections
 */
class DatGralOpe extends ElectronicDocumentSectionBase {

    protected $attributes = ['dFeEmiDE' => null, 'gOpeCom' => null, 'gEmis' => null, 'gDatRec' => null];

    public function getDFeEmiDEAttribute()
    {
        if ( ! isset($this->attributes['dFeEmiDE'])) {
            $this->attributes['dFeEmiDE'] = ($this->root->ed()->exists) ? $this->root->ed()->created_at : $this->createDate();
        }

        return $this->dateTimeToString($this->attributes['dFeEmiDE']);
    }

    public function toArray()
    {
        $attributes = array_merge([
            'dFeEmiDE' => $this->dFeEmiDE
        ], parent::toArray()); // TODO: Change the autogenerated stub

        if ($this->root->gTimb->iTiDE === 7) $attributes = Arr::except($attributes, ['gOpeCom']);

        return $attributes;
    }
}