<?php

namespace Mcarral\Sifen\Entities\ElectronicDocumentSections;

use Illuminate\Support\Arr;

/**
 * Class DtipDE
 * @property-read CamFE gCamFE
 * @property-read CamAE gCamAE
 * @property-read CamNRE gCamNRE
 * @property-read CamCond gCamCond
 * @property-read SectionCollection|CamItem[] gCamItem
 * @property CamNCDE gCamNCDE
 * @property-read Transp gTransp
 * @package Mcarral\Sifen\Entities\ElectronicDocumentSections
 */
class DtipDE extends ElectronicDocumentSectionBase {

    protected $attributes = [
        'gCamFE' => null, 'gCamAE' => null, 'gCamNCDE' => null,'gCamNRE' => null, 'gCamCond' => null, 'gCamItem' => null,
        'gTransp' => null,
    ];

    /**
     * @return array
     */
    public function rules()
    {
        return [
            'gCamFE'        => 'required_if:gTim.iTiDE,1,2',    // Campos que componen la FE
            'gCamAE'        => 'required_if:gTim.iTiDE,4',      // Campos que componen la AE
            'gCamNCDE'      => 'required_if:gTim.iTiDE,5,6',    // Campos que componen la NCDE
            'gCamNRE'       => 'required_if:gTim.iTiDE,7',      // Campos que componen la NRE
            'gCamItem'      => ['required', 'min:2'],           // Lista de items
        ];
    }

    protected function validateAdditionalData()
    {
        return array_merge(parent::validateAdditionalData(), [
            'gTimb.iTiDE' => $this->root->gTimb->iTiDE,
        ]); // TODO: Change the autogenerated stub
    }

    public function toArray()
    {
        $attributes = array_merge(parent::toArray(), [
            'gCamFE'        => $this->gCamFE,
        ]);
        if (! in_array($this->root->gTimb->iTiDE, [1])) $attributes = Arr::except($attributes, ['gCamFE']);
        if (! in_array($this->root->gTimb->iTiDE, [4])) $attributes = Arr::except($attributes, ['gCamAE']);
        if (! in_array($this->root->gTimb->iTiDE, [1, 2, 4])) $attributes = Arr::except($attributes, ['gCamCond']);
        if (! in_array($this->root->gTimb->iTiDE, [5, 6])) $attributes = Arr::except($attributes, ['gCamNCDE']);
        if (! in_array($this->root->gTimb->iTiDE, [7])) $attributes = Arr::except($attributes, ['gCamNRE', 'gTransp']);

        return $attributes;
    }

}
