<?php

namespace Mcarral\Sifen\Entities\ElectronicDocumentSections;

/**
 * Class InfPed
 * @property string dConPed
 * @property string dInfInt
 * @package Mcarral\Sifen\Entities\ElectronicDocumentSections
 */
class InfPed extends ElectronicDocumentSectionBase {

    protected $fillable = ['dConPed', 'dInfInt'];

    public function rules()
    {
        return array_merge(parent::rules(), [
            'dConPed' => ['string', 'between:1,20'], // Control de pedido de compra
            'dInfInt' => ['string', 'between:0,500'], // Información de interés del emisor con respecto al pedido de compra
        ]); // TODO: Change the autogenerated stub
    }
}