<?php

namespace Mcarral\Sifen\Entities\ElectronicDocumentSections;

use Mcarral\Sifen\Entities\ElectronicDocument;
use Mcarral\Sifen\Support\SimpleXMLElement;

/**
 * Class DE
 * @property int dVerFor
 * @property-read DE gDE
 * @property-read CamFuFD gCamFuFD
 * @package Mcarral\Sifen\Entities\ElectronicDocumentSections
 * @mixin DE
 */
class Root extends ElectronicDocumentSectionBase {

    protected $ed;

    protected $attributes = ['dVerFor' => null, 'gDE' => null, 'gCamFuFD' => null];

    protected $fillable = ['dVerFor', 'gDE', 'gCamFuFD'];

    protected $redirectNode = 'gDE';

    public function __construct($ed)
    {
        parent::__construct($this);

        $this->ed = $ed;
    }

    /**
     * @return $this
     */
    public function defaults()
    {
        $this->dVerFor = $this->ekuatia->versionInt();

        return $this;
    }

    public function sectionName()
    {
        return 'rDE';
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            'dVerFor'   => 'required|integer|digits_between:1,4',   // Versión del formato
            //'gCamFuFD'  => '',    // Campos fuera de la firma digital
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * @return ElectronicDocument
     */
    public function ed()
    {
        return $this->ed;
    }

    /**
     * @return \Mcarral\Sifen\Support\SimpleXMLElement
     */
    protected function xmlElementInstance()
    {
        return new SimpleXMLElement(
            '<?xml version="1.0" encoding="UTF-8"?>
             <' . $this->sectionName() . ' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://ekuatia.set.gov.py/sifen/xsd" xsi:schemaLocation="http://ekuatia.set.gov.py/sifen/xsd/ ' . basename(ekuatia()->schema('siRecepDE')) . '"/>'
        );
    }

    protected function afterSigned(SimpleXMLElement $xml, $objDSig)
    {
        // set signature to qr section
        $this->gCamFuFD->setSignature(
            $objDSig->sigNode
        );

        return $xml;
    }

    protected function signId()
    {
        return $this->dIDE;
    }

    protected function afterAppendSection($key, SimpleXMLElement $xml)
    {
        if ($key != "gDE") return;
        $this->sign($xml);
    }

    public function toArray()
    {
        return array_merge(parent::toArray(), [
            //'gCamFuFD'  => $this->gCamFuFD,
        ]); // TODO: Change the autogenerated stub
    }
}