<?php

namespace Mcarral\Sifen\Entities\ElectronicDocumentSections;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Validation\Rule;

/**
 * Class ValorRestaItem
 * @property int dDescItem
 * @property int dPorcDesIt
 * @property int dDescGloItem
 * @property int dAntPreUniIt
 * @property int dAntGloPreUniIt
 * @property int dTotOpeItem
 * @package Mcarral\Sifen\Entities\ElectronicDocumentSections
 */
class ValorRestaItem extends ElectronicDocumentSectionBase {

    protected $attributes = ['dDescItem' => null, 'dPorcDesIt' => null,
                             'dDescGloItem' => null, 'dAntPreUniIt' => null, 'dAntGloPreUniIt' => null,
                             'dTotOpeItem' => null];

    protected $fillable = ['dTotOpeItem'];

    public function defaults()
    {
        $this->dPorcDesIt = 0;
        $this->dDescGloItem = 0;
        $this->dAntPreUniIt = 0;
        $this->dAntGloPreUniIt = 0;

        return parent::defaults(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            'dDescItem'         => 'numeric|ekuatia_long:1-23p0-8',
            'dPorcDesIt'        => 'required_with:dDescItem|numeric|ekuatia_long:1-3p0-2',
            'dDescGloItem'      => 'numeric|ekuatia_long:1-15p0-8',
            'dAntPreUniIt'      => 'numeric|ekuatia_long:1-15p0-8',
            'dAntGloPreUniIt'   => 'numeric|ekuatia_long:1-15p0-8',
            'dTotOpeItem'       => 'required|numeric|ekuatia_long:1-23p0-8',
        ]);
    }

    public function rulesAttributes()
    {
        return array_merge(parent::rulesAttributes(), [
            'dDescItem'      => 'Descuento en el precio unitario del producto y/o servicio por ítem',
            'dPorcDesIt'     => 'Porcentaje de descuento por ítem',
            'dDescGloItem'   => 'Descuento global sobre el precio unitario por ítem (incluidos impuestos)',
            'dAntPreUniIt'   => 'Anticipo particular sobre el precio unitario por ítem (incluidos impuestos)',
            'dAntGloPreUniIt'=> 'Anticipo global sobre el precio unitario por ítem (incluidos impuestos)',
            'dTotOpeItem'    => 'Valor total de la venta por ítem',
        ]); // TODO: Change the autogenerated stub
    }

    protected function validating(Validator $validator)
    {
        if (in_array($this->root->gDatGralOpe->gOpeCom->iTImp, [1, 3, 4, 5])) {
            $dTotOpeItem = ($this->parent->dPUniProSer - $this->dDescItem - $this->dDescGloItem - $this->dAntPreUniIt - $this->dAntGloPreUniIt) * $this->parent->parent->dCantProSer;
            if (abs($this->dTotOpeItem - $dTotOpeItem) > 0.5) {
                $validator->getMessageBag()->add('dTotOpeItem', 'Existe una diferencia mayor a 0.5 en el total (' . $this->dTotOpeItem . ') item.  [' . $dTotOpeItem . ']');
            }
        }
    }

    protected function setDDescItemAttribute($value)
    {
        $this->attributes['dDescItem'] = $value ? $value : 0;
    }

    protected function getDDescItemAttribute()
    {
        return ! is_null($this->attributes['dDescItem']) ? ekuatia_number_format($this->attributes['dDescItem'], 8) : null;
    }

    protected function getDPorcDesItAttribute()
    {
        return ! is_null($this->attributes['dPorcDesIt']) ? ekuatia_number_format($this->attributes['dPorcDesIt'], 2) : null;
    }

    protected function setDTotOpeItemAttribute($value)
    {
        $this->attributes['dTotOpeItem'] = $value ? $value : 0;

    }

    protected function getDTotOpeItemAttribute()
    {
        $value = ! is_null($this->attributes['dTotOpeItem']) ? $this->attributes['dTotOpeItem'] : null;
        if ( is_null($value)) {
            $value = ($this->parent->dPUniProSer - $this->dDescItem) * $this->parent->parent->dCantProSer;
        }

        return ekuatia_number_format($value, 8);
    }
}
