<?php

namespace Mcarral\Sifen\Entities\ElectronicDocumentSections;

/**
 * Class CvalorItem
 * @property int dPUniProSer
 * @property int dTotBruOpeItem
 * @property-read ValorRestaItem gValorRestaItem
 * @package Mcarral\Sifen\Entities\ElectronicDocumentSections
 */
class ValorItem extends ElectronicDocumentSectionBase {

    protected $attributes = ['dPUniProSer' => null, 'dTotBruOpeItem' => null, 'gValorRestaItem' => null];

    protected $fillable = ['dPUniProSer'];

    public function defaults()
    {

        return parent::defaults(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            'dPUniProSer'   => 'required|numeric|ekuatia_long:1-23p0-8',
            'dTotBruOpeItem'=> 'required|numeric|ekuatia_long:1-23p0-8',
        ]); // TODO: Change the autogenerated stub
    }

    public function rulesAttributes()
    {
        return array_merge(parent::rulesAttributes(), [
            'dPUniProSer'    => 'Precio unitario del producto y/o servicio',
            'dTotBruOpeItem' => 'Total bruto de la operación por ítem',
        ]);
    }

    protected function setDPUniProSerAttribute($value)
    {
        $this->attributes['dPUniProSer'] = is_null($value) ? $value : abs($value);
    }

    protected function getDPUniProSerAttribute()
    {
        return ! is_null($this->attributes['dPUniProSer']) ? ekuatia_number_format($this->attributes['dPUniProSer'], 8) : null;
    }

    protected function setDTotBruOpeItemAttribute($value) {
        $this->attributes['dTotBruOpeItem'] = $value ? $value : 0;
    }

    protected function getDTotBruOpeItemAttribute() {
        $value = ! is_null($this->attributes['dTotBruOpeItem']) ? $this->attributes['dTotBruOpeItem'] : null;
        if (is_null($value)) {
            $value = $this->dPUniProSer * $this->parent->dCantProSer;
        }

        return ekuatia_number_format($value, 8);
    }
}